// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskStatus string

const (
	TaskStatusPENDING   TaskStatus = "PENDING"
	TaskStatusCOMPLETED TaskStatus = "COMPLETED"
	TaskStatusCANCELLED TaskStatus = "CANCELLED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Todo struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Duedate     pgtype.Date      `json:"duedate"`
	Status      NullTaskStatus   `json:"status"`
	Createdat   pgtype.Timestamp `json:"createdat"`
	Updatedat   pgtype.Timestamp `json:"updatedat"`
}
