apiVersion: v1
kind: ConfigMap
metadata:
  name: todolist-configmap
data:
    POSTGRES_CONNECTION: postgresql://postgres:password@postgres-service:5432/todolist?sslmode=disable
    PORT: "4000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: todolist-server:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"       # minimum CPU requested (0.1 core)
            memory: "128Mi"   # minimum memory requested
          limits:
            cpu: "500m"       # max CPU (0.5 core)
            memory: "256Mi"
        envFrom:
            - configMapRef:
                name: todolist-configmap
        ports:
        - containerPort: 4000   

---

apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  selector:
    app: todolist
  type: NodePort 
  ports:
    - port: 80         # Cluster IP port
      targetPort: 4000 
      nodePort: 30081
